In [11]:
import polars as pl

pl.scan_parquet(
    "s3://aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.268/consolidated/units.parquet"
).filter(pl.col('structure') == 'MOs').collect()

shape: (64_265, 60)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬──────┐
│ activity_d ┆ amplitude  ┆ amplitude_ ┆ amplitude_ ┆ … ┆ date      ┆ subject_i ┆ session_i ┆ id   │
│ rift       ┆ ---        ┆ cutoff     ┆ cv_median  ┆   ┆ ---       ┆ d         ┆ d         ┆ ---  │
│ ---        ┆ f64        ┆ ---        ┆ ---        ┆   ┆ date      ┆ ---       ┆ ---       ┆ i64  │
│ f64        ┆            ┆ f64        ┆ f64        ┆   ┆           ┆ i64       ┆ str       ┆      │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪══════╡
│ 0.58038    ┆ 119.120087 ┆ 0.000515   ┆ null       ┆ … ┆ 2022-07-2 ┆ 620263    ┆ 620263_20 ┆ 1494 │
│            ┆            ┆            ┆            ┆   ┆ 6         ┆           ┆ 22-07-26  ┆      │
│ 0.087932   ┆ 130.473761 ┆ 0.000135   ┆ null       ┆ … ┆ 2022-07-2 ┆ 620263    ┆ 620263_20 ┆ 1495 │
│            ┆            ┆            ┆            ┆   ┆ 6         ┆           ┆ 22-07-26  ┆      │
│ 0.150351   ┆ 110.746181 ┆ null       ┆ null       ┆ … ┆ 2022-07-2 ┆ 620263    ┆ 620263_20 ┆ 1496 │
│            ┆            ┆            ┆            ┆   ┆ 6         ┆           ┆ 22-07-26  ┆      │
│ 0.681116   ┆ 206.261719 ┆ 0.001172   ┆ null       ┆ … ┆ 2022-07-2 ┆ 620263    ┆ 620263_20 ┆ 1497 │
│            ┆            ┆            ┆            ┆   ┆ 6         ┆           ┆ 22-07-26  ┆      │
│ 0.014266   ┆ 224.193451 ┆ null       ┆ null       ┆ … ┆ 2022-07-2 ┆ 620263    ┆ 620263_20 ┆ 1498 │
│            ┆            ┆            ┆            ┆   ┆ 6         ┆           ┆ 22-07-26  ┆      │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …    │
│ 0.177931   ┆ 704.148346 ┆ 0.00031    ┆ null       ┆ … ┆ 2024-12-0 ┆ 762124    ┆ 762124_20 ┆ 642  │
│            ┆            ┆            ┆            ┆   ┆ 2         ┆           ┆ 24-12-02  ┆      │
│ 0.007718   ┆ 111.38517  ┆ null       ┆ null       ┆ … ┆ 2024-12-0 ┆ 762124    ┆ 762124_20 ┆ 638  │
│            ┆            ┆            ┆            ┆   ┆ 2         ┆           ┆ 24-12-02  ┆      │
│ 0.022388   ┆ 118.095177 ┆ 0.000446   ┆ 0.2293     ┆ … ┆ 2024-12-0 ┆ 762124    ┆ 762124_20 ┆ 639  │
│            ┆            ┆            ┆            ┆   ┆ 2         ┆           ┆ 24-12-02  ┆      │
│ 0.03631    ┆ 109.315418 ┆ 0.000449   ┆ 0.2847     ┆ … ┆ 2024-12-0 ┆ 762124    ┆ 762124_20 ┆ 640  │
│            ┆            ┆            ┆            ┆   ┆ 2         ┆           ┆ 24-12-02  ┆      │
│ 0.130903   ┆ 605.330231 ┆ null       ┆ null       ┆ … ┆ 2024-12-0 ┆ 762124    ┆ 762124_20 ┆ 641  │
│            ┆            ┆            ┆            ┆   ┆ 2         ┆           ┆ 24-12-02  ┆      │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴──────┘

In [14]:
import polars as pl

(
    pl.scan_parquet(
        "s3://aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.268/consolidated/units.parquet"
    )
    .join(
        pl.scan_parquet(
            "s3://aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.268/consolidated/session.parquet"
        ).filter(
            pl.col('keywords').list.contains('ccf'),
            pl.col('keywords').list.contains('task'),
            pl.col('keywords').list.contains('production'),
            ~pl.col('keywords').list.contains('issues'),
            ~pl.col('keywords').list.contains('templeton'),
        ),
        on=['session_id'],
        how='semi',
    )
    .with_columns(
        (
            
        pl.col('activity_drift').le(0.2) & pl.col('amplitude_cutoff').le(0.1)
        & pl.col('presence_ratio').ge(0.7)
        & pl.col('isi_violations_ratio').le(0.5)
        & pl.col('decoder_label').ne('noise')
        & pl.col('firing_rate').ge(1)
        ).alias('is_good')
    )
    .group_by('session_id')
    .agg(
        pl.col('unit_id').filter('is_good').n_unique().alias('num_good_units'),
        pl.col('unit_id').filter(~pl.col('is_good')).n_unique().alias('num_bad_units'),
    )
    .sort('num_good_units')
    .collect()
)

shape: (157, 3)
┌───────────────────┬────────────────┬───────────────┐
│ session_id        ┆ num_good_units ┆ num_bad_units │
│ ---               ┆ ---            ┆ ---           │
│ str               ┆ u32            ┆ u32           │
╞═══════════════════╪════════════════╪═══════════════╡
│ 759434_2025-02-03 ┆ 78             ┆ 910           │
│ 626791_2022-08-16 ┆ 191            ┆ 1371          │
│ 714753_2024-07-02 ┆ 229            ┆ 641           │
│ 708016_2024-04-30 ┆ 273            ┆ 349           │
│ 699847_2024-04-15 ┆ 277            ┆ 912           │
│ …                 ┆ …              ┆ …             │
│ 686176_2023-12-04 ┆ 1334           ┆ 3285          │
│ 715710_2024-07-18 ┆ 1362           ┆ 3011          │
│ 733780_2024-09-03 ┆ 1397           ┆ 3046          │
│ 681532_2023-10-16 ┆ 1440           ┆ 2178          │
│ 733780_2024-09-04 ┆ 1598           ┆ 2620          │
└───────────────────┴────────────────┴───────────────┘

In [6]:
import polars as pl

(
    pl.scan_parquet(
        "s3://aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.268/consolidated/trials.parquet"
    )
    .filter(
        pl.col('response_time').is_not_null() & pl.col('task_control_response_time').is_null(),
    )   
    .collect()
)

shape: (273, 52)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬─────┐
│ start_time ┆ stop_time  ┆ quiescent_ ┆ quiescent_ ┆ … ┆ date       ┆ subject_i ┆ session_i ┆ id  │
│ ---        ┆ ---        ┆ start_time ┆ stop_time  ┆   ┆ ---        ┆ d         ┆ d         ┆ --- │
│ f64        ┆ f64        ┆ ---        ┆ ---        ┆   ┆ date       ┆ ---       ┆ ---       ┆ i64 │
│            ┆            ┆ f64        ┆ f64        ┆   ┆            ┆ i64       ┆ str       ┆     │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═════╡
│ 604.1497   ┆ 608.67007  ┆ 604.1497   ┆ 605.61751  ┆ … ┆ 2022-07-27 ┆ 620263    ┆ 620263_20 ┆ 110 │
│            ┆            ┆            ┆            ┆   ┆            ┆           ┆ 22-07-27  ┆     │
│ 140.05761  ┆ 145.56228  ┆ 140.05761  ┆ 141.52548  ┆ … ┆ 2022-08-15 ┆ 626791    ┆ 626791_20 ┆ 8   │
│            ┆            ┆            ┆            ┆   ┆            ┆           ┆ 22-08-15  ┆     │
│ 1322.4811  ┆ 1326.98479 ┆ 1322.4811  ┆ 1323.94899 ┆ … ┆ 2022-09-19 ┆ 628801    ┆ 628801_20 ┆ 150 │
│            ┆            ┆            ┆            ┆   ┆            ┆           ┆ 22-09-19  ┆     │
│ 1380.76272 ┆ 1385.26648 ┆ 1380.76272 ┆ 1382.23061 ┆ … ┆ 2022-09-19 ┆ 628801    ┆ 628801_20 ┆ 157 │
│            ┆            ┆            ┆            ┆   ┆            ┆           ┆ 22-09-19  ┆     │
│ 1942.09526 ┆ 1946.59893 ┆ 1942.09526 ┆ 1943.56305 ┆ … ┆ 2022-09-19 ┆ 628801    ┆ 628801_20 ┆ 229 │
│            ┆            ┆            ┆            ┆   ┆            ┆           ┆ 22-09-19  ┆     │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …   │
│ 1164.77268 ┆ 1170.27732 ┆ 1164.77268 ┆ 1166.24061 ┆ … ┆ 2025-03-18 ┆ 762526    ┆ 762526_20 ┆ 77  │
│            ┆            ┆            ┆            ┆   ┆            ┆           ┆ 25-03-18  ┆     │
│ 1868.26207 ┆ 1873.76668 ┆ 1868.26207 ┆ 1869.72994 ┆ … ┆ 2025-03-18 ┆ 762526    ┆ 762526_20 ┆ 182 │
│            ┆            ┆            ┆            ┆   ┆            ┆           ┆ 25-03-18  ┆     │
│ 799.13008  ┆ 804.63467  ┆ 799.13008  ┆ 800.59797  ┆ … ┆ 2025-03-19 ┆ 762526    ┆ 762526_20 ┆ 20  │
│            ┆            ┆            ┆            ┆   ┆            ┆           ┆ 25-03-19  ┆     │
│ 2586.92763 ┆ 2592.44886 ┆ 2586.92763 ┆ 2588.39543 ┆ … ┆ 2025-03-19 ┆ 762526    ┆ 762526_20 ┆ 278 │
│            ┆            ┆            ┆            ┆   ┆            ┆           ┆ 25-03-19  ┆     │
│ 3742.0115  ┆ 3747.56616 ┆ 3742.0115  ┆ 3743.49609 ┆ … ┆ 2025-03-19 ┆ 762526    ┆ 762526_20 ┆ 450 │
│            ┆            ┆            ┆            ┆   ┆            ┆           ┆ 25-03-19  ┆     │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴─────┘

In [42]:
tagged_cols =     pl.selectors.starts_with('is') & pl.selectors.ends_with('tagged') & ~pl.selectors.contains('_not_')

df = pl.DataFrame({'is_short_tagged':[False], 'is_unresponsive': [True]})

df.filter(pl.sum_horizontal(tagged_cols).eq(1) & pl.col('is_unresponsive')).is_empty()

True

In [ ]:
import math
from typing import Iterable

import polars_ds as pds

def psth(df: pl.DataFrame, response_col, duration_col: str, group_by: str | list[str] | None='index', bin_size=0.001, conv_kernel = 0.005, parallel=True) -> pl.DataFrame:
    """
    Compute the peristimulus time histogram (PSTH) for a given response and duration.
    
    Parameters:
    - df: DataFrame containing the response and duration columns.
    - response_col: Name of the column containing the response data, list[float]
    - duration_col: Name of the column containing the duration, float
    - bin_size: Size of the bins for the histogram in the same units as the response values
    
    Returns:
    - DataFrame with PSTH results.
    """
    if isinstance(group_by, str) or not isinstance(group_by, Iterable):
        group_by = [group_by]
    n_bins = pl.col(duration_col).first().truediv(bin_size).ceil().cast(int)
    bin_edges = pl.linear_space(0, pl.col(duration_col).first(), 1 + n_bins, closed='both')
    bin_centers = pl.linear_space(bin_size / 2, pl.col(duration_col).first() - bin_size / 2, n_bins)
    conv_kernel_size: int = math.ceil(conv_kernel / bin_size)
    return (
        df
        .with_row_index()
        .explode(response_col)
        .group_by(group_by)
        .agg(
            pl.all().exclude(response_col),
            psth=pds.convolve(pl.col(response_col).hist(bins=bin_edges, include_breakpoint=False), kernel=[1]*conv_kernel_size, mode='same', parallel=parallel).truediv(conv_kernel_size * pl.col('index').n_unique()),#,
            # psth=pds.convolve(pl.col(response_col).hist(bins=bin_edges, include_breakpoint=False), kernel=[1]*conv_kernel_size, mode='full', parallel=parallel).slice(conv_kernel_size-1, n_bins).truediv(conv_kernel_size * pl.col('index').n_unique()),#,
            unconv_psth=pl.col(response_col).hist(bins=bin_edges, include_breakpoint=False),
            bin_centers=bin_centers,
        )
        ## DEBUGGING: check lengths of list columns created above -  should all be equal
        # .with_columns(
        #     pl.col('psth', 'unconv_psth', 'bin_centers').list.len(), 
        # )
        .drop('index')
    )
    

pl.DataFrame({
    'response': [[], [0.001, 0.0012, 0.0022, 0.004, 0.0066, 0.009], [0.0022, 0.0033, 0.008, 0.009, 0.01]],
    'duration': [0.01, 0.01, 0.01],
    'unit_id': [2, 1, 0],
}).pipe(psth, 'response', 'duration', group_by=['duration', 'unit_id'], bin_size=0.001, conv_kernel=0.003).explode('psth', 'unconv_psth', 'bin_centers').unpivot(on=['psth', 'unconv_psth'], index=['bin_centers', 'duration', 'unit_id']).plot.line(x='bin_centers', y='value', color='variable', row='unit_id')

alt.Chart(...)