In [1]:
import altair as alt
import polars as pl
import numpy as np

df = pl.DataFrame(
    {
        # "x": [0, 1, 2, 3, 3, 4, 5],
        "y": [0, 1, 2, None, 3, 4, 5],
    }
)
df.to_pandas()

     y
0  0.0
1  1.0
2  2.0
3  NaN
4  3.0
5  4.0
6  5.0

In [122]:
(
    alt.Chart(df.to_pandas())
    .transform_calculate(
        metric=f'datum.y'
    )
    .transform_filter("isValid(datum.metric)")
    .transform_window(
        cdf="cume_dist()", 
        sort=[{"field": "x"}],
    )
    .encode(x='metric:Q', y='cdf:Q')
    .mark_line(
        point=True,             
        interpolate="step-after",
    )
)

alt.Chart(...)

In [ ]:
        # .transform_filter(
        #     alt.FieldLTEPredicate('metric', alt.expr.quantileUniform(0.9))
        # )

In [156]:
df = pl.DataFrame({'x':[100.] + list(np.random.normal(loc=0.0, scale=1.0, size=1000))})

In [186]:
df.quantile(0.5)

shape: (1, 1)
┌───────────┐
│ x         │
│ ---       │
│ f64       │
╞═══════════╡
│ -0.030601 │
└───────────┘

In [221]:
df
(
    alt.Chart(df.to_pandas())
    # .transform_calculate(
    #     metric=f'datum.x'
    # )
    .transform_calculate(
        upper=f'quantileUniform(datum.x, 0.9)'
    )
    # .transform_filter(
        # alt.datum.x < 10, # <- this works
        # alt.FieldLTEPredicate('x', 3), # <- this works
        # 'datum.x < 13' # <- this works
        # 'datum.x <= quantileUniform(datum.x)' 
        # alt.datum.x <= alt.expr.quantileUniform(alt.datum.x,  probs=0.1)
    # )
    .mark_line()
    .encode(
        x=alt.X('x:Q', bin=alt.Bin(maxbins=100)),
        y='count()',
    )
)

alt.Chart(...)

In [4]:
np.searchsorted([1, 2, 3, 4, 5, 9], [[10, 11], [2,4], [6,8]])

array([[6, 6],
       [1, 3],
       [5, 5]])